# Generated by Django 4.0.6 on 2022-08-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0005_alter_reviews_rating_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
